version: '2'

services:
  master_db:
    image: 'bitnami/postgresql:latest'
    container_name: master_db
    ports:
      - '5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=cain
      - POSTGRESQL_PASSWORD=1955
      - POSTGRESQL_DATABASE=cain
  slave_db:
    image: 'bitnami/postgresql:latest'
    container_name: slave_db
    ports:
      - '5432'
    depends_on:
      - master_db
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=master_db
      - POSTGRESQL_PASSWORD=1955
      - POSTGRESQL_MASTER_PORT_NUMBER=5432

volumes:
  postgresql_master_data:
